name: lint
on: push
jobs:
  Lint:
    name: Lint checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Download golangci-lint
        run: |
          wget https://github.com/golangci/golangci-lint/releases/download/v1.41.0/golangci-lint-1.41.0-linux-amd64.tar.gz
          tar -xvf ./golangci-lint-1.41.0-linux-amd64.tar.gz
      - name: Running golangci-lint
        env:
          GO111MODULE: on
          GOPATH: /home/runner/work/
        run: GOLINTER=./golangci-lint-1.41.0-linux-amd64/golangci-lint make lint
